version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres-product-container
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pg-data:/var/lib/postgresql/product_data
    ports:
      - "5432:5432"

  product_service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
volumes:
  pg-data: