apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: peetsss/microecommerce_cart
        ports:
        - containerPort: 27017
        env:
        - name: CART_MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-cart-host
        - name: CART_MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: CART_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: CART_MONGODB_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-cart-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: peetsss/microecommerce_order
        ports:
        - containerPort: 27017
        env:
        - name: ORDER_MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-order-host
        - name: ORDER_MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: ORDER_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: ORDER_MONGODB_DB
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-order-db
        - name: CART_SERVICE_NAME
          value: "cart-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: peetsss/microecommerce_product
        ports:
        - containerPort: 5432
        env:
        - name: PRODUCT_POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-product-host
        - name: PRODUCT_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: PRODUCT_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: PRODUCT_POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-product-db
        - name: PRODUCT_POSTGRES_PORT
          value: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: peetsss/microecommerce_user
        ports:
        - containerPort: 5432
        env:
        - name: USER_POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-user-host
        - name: USER_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: USER_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: USER_POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-user-db
        - name: USER_POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: orde-service
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: product
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000