name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Run tests
      run: |
        python -m pytest ./src/cart/tests
        python -m pytest ./src/user/tests
        python -m pytest ./src/product/tests
        python -m pytest ./src/order/tests
        python -m pytest ./src/tests

    - name: Stop Docker Compose
      run: docker-compose down