name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt

    - name: Add execute permissions to start-test.sh
      run: chmod +x ./src/tests/start-test.sh

    - name: Setup containers and run unit tests
      run: docker-compose -f ./src/docker-compose.tests up -d

    - name: Wait for completion of unit tests and check results
      run: |
        set -e
        sleep 20
        docker-compose -f ./src/docker-compose.tests logs
        container_id=$(docker-compose -f ./src/docker-compose.tests ps -q test)
        exit_code=$(docker inspect -f '{{.State.ExitCode}}' $container_id)
        docker-compose -f ./src/docker-compose.tests down
        if [ $exit_code -ne 0 ]; then
          exit 1
        fi

    - name: Setup containers for integration tests
      run: docker-compose -f ./src/docker-compose.yml up -d

    - name: Run integration tests
      run: |
        sleep 5
        pytest ./src/tests

    - name: Wait for completion of integration tests and results
      run: |
        sleep 5
        docker-compose -f ./src/docker-compose.yml down