name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt

    - name: Run unit tests
      run: docker-compose -f ./src/docker-compose.tests up -d
      env:
        USER_POSTGRES_HOST: ${{ secrets.USER_POSTGRES_HOST }}
        USER_POSTGRES_PORT: ${{ secrets.USER_POSTGRES_PORT }}
        USER_POSTGRES_USER: ${{ secrets.USER_POSTGRES_USER }}
        USER_POSTGRES_PASSWORD: ${{ secrets.USER_POSTGRES_PASSWORD }}
        USER_POSTGRES_DB: ${{ secrets.USER_POSTGRES_DB }}
        PRODUCT_POSTGRES_HOST: ${{ secrets.PRODUCT_POSTGRES_HOST }}
        PRODUCT_POSTGRES_PORT: ${{ secrets.PRODUCT_POSTGRES_PORT }}
        PRODUCT_POSTGRES_USER: ${{ secrets.PRODUCT_POSTGRES_USER }}
        PRODUCT_POSTGRES_PASSWORD: ${{ secrets.PRODUCT_POSTGRES_PASSWORD }}
        PRODUCT_POSTGRES_DB: ${{ secrets.PRODUCT_POSTGRES_DB }}
        CART_MONGODB_HOST: ${{ secrets.CART_MONGODB_HOST }}
        CART_MONGODB_USER: ${{ secrets.CART_MONGODB_USER }}
        CART_MONGODB_PASSWORD: ${{ secrets.CART_MONGODB_PASSWORD }}
        CART_MONGODB_DB: ${{ secrets.CART_MONGODB_DB }}
        ORDER_MONGODB_HOST: ${{ secrets.ORDER_MONGODB_HOST }}
        ORDER_MONGODB_USER: ${{ secrets.ORDER_MONGODB_USER }}
        ORDER_MONGODB_PASSWORD: ${{ secrets.ORDER_MONGODB_PASSWORD }}
        ORDER_MONGODB_DB: ${{ secrets.ORDER_MONGODB_DB }}
        TESTING: True

    - name: Stop Docker Compose
      run: docker-compose -f ./src/docker-compose.tests down
    
    - name: Test integration
      run: docker-compose up -d
      env:
        USER_POSTGRES_HOST: ${{ secrets.USER_POSTGRES_HOST }}
        USER_POSTGRES_PORT: ${{ secrets.USER_POSTGRES_PORT }}
        USER_POSTGRES_USER: ${{ secrets.USER_POSTGRES_USER }}
        USER_POSTGRES_PASSWORD: ${{ secrets.USER_POSTGRES_PASSWORD }}
        USER_POSTGRES_DB: ${{ secrets.USER_POSTGRES_DB }}
        PRODUCT_POSTGRES_HOST: ${{ secrets.PRODUCT_POSTGRES_HOST }}
        PRODUCT_POSTGRES_PORT: ${{ secrets.PRODUCT_POSTGRES_PORT }}
        PRODUCT_POSTGRES_USER: ${{ secrets.PRODUCT_POSTGRES_USER }}
        PRODUCT_POSTGRES_PASSWORD: ${{ secrets.PRODUCT_POSTGRES_PASSWORD }}
        PRODUCT_POSTGRES_DB: ${{ secrets.PRODUCT_POSTGRES_DB }}
        CART_SERVICE_NAME: ${{ secrets.CART_SERVICE_NAME }}
        CART_MONGODB_HOST: ${{ secrets.CART_MONGODB_HOST }}
        CART_MONGODB_USER: ${{ secrets.CART_MONGODB_USER }}
        CART_MONGODB_PASSWORD: ${{ secrets.CART_MONGODB_PASSWORD }}
        CART_MONGODB_DB: ${{ secrets.CART_MONGODB_DB }}
        ORDER_MONGODB_HOST: ${{ secrets.ORDER_MONGODB_HOST }}
        ORDER_MONGODB_USER: ${{ secrets.ORDER_MONGODB_USER }}
        ORDER_MONGODB_PASSWORD: ${{ secrets.ORDER_MONGODB_PASSWORD }}
        ORDER_MONGODB_DB: ${{ secrets.ORDER_MONGODB_DB }}

    - name: Run integration tests
      run: |
        sleep 30
        pytest ./src/tests

    - name: Stop Docker Compose
      run: docker-compose down